package github.yeori.beautifuldb;

public enum Error {

	NOT_FOUND,
	EXISTING_REVERSE_EDGE,
	EXISTING_FOREIGN_KEY,
	DIFFERENT_SCHEMA,
	INVALID_AUTH_KEY,
	SERVER_ERROR,
	
	INVALID_MAG_FORMAT, INVALID_COLUMN_TYPE, NO_SUCH_COLUMN
}
